### ISSUE TITLE
kinda useless

### ISSUE THREAD

**Issue by Egduffuu** [Blobby-Boi/uBlobeBM#2]
it doesnt let u run on privileged pages (like google classroom) so its just like running a bookmarklet normally :( but if u have an idea on how 2 use plz tell mee

**Comment by Blobby-Boi** [comment]
for me it can run on google classroom just fine?
though its not supposed to be able to run on privilleged pages its meant for people who have bookmarklets blocked for them by their district. If you dont have bookmarklets blocked, then dont use this
